version: "3.9"

services:
  backend:
    build: ./server
    container_name: groweasy-backend
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    container_name: groweasy-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:4000
    depends_on:
      - backend